from django.urls import path
from . import views
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('', views.home, name='home'),
    path('configuration', views.config, name='config'),
    path('configuration/error', views.configerror, name='configerror'),
    path('not-found', views.error404, name='error404'),
    path('term/', views.term, name='term'),
    path('view-term/', views.viewterm, name='viewterm'),
    path('switch-term/', views.switchterm, name='switchterm'),
    path('create-term/', views.createterm, name='createterm'),
    path('term/error/', views.termerror, name='termerror'),
    path('session/', views.session, name='session'),
    path('view-session/', views.viewsession, name='viewsession'),
    path('switch-session/', views.switchsession, name='switchsession'),
    path('create-session/', views.createsession, name='createsession'),
    path('class/', views.group, name='class'),
    path('class/remove/<str:pk>/', views.removeclassteacher, name='remove_class_teacher'),
    path('class/deactivate/<str:pk>/', views.deactivateclass, name='deactivate_class'),
    path('class/activate/<str:pk>/', views.activateclass, name='activate_class'),
    path('subject/', views.subject, name='subject'),
    path('arm/', views.arm, name='arm'),
    path('view-arm/', views.viewarm, name='viewarm'),
    path('create-arm/', views.createarm, name='createarm'),
    path('login/', views.loginuser, name='login'),
    path('logout/', views.logoutuser, name='logout'),
    path('role/', views.newrole, name='role'),
    path('student/', views.student, name='student'),
    path('register-student/', views.registerstudent, name='register_student'),
    path('register-student/next-of-kin/', views.registerstudentnok, name='student_entry'),
    path('manage-student/entry/', views.getstudent, name='get_student'),
    path('manage-student/<str:pk>/', views.managestudent, name='manage_student'),
    path('transfer-student/', views.transferstudent, name='transfer_student'),
    path('disable-student/', views.disablestudent, name='disable_student'),
    path('enable-student/', views.enablestudent, name='enable_student'),
    path('edit-student-reg/', views.editreg, name='edit_reg'),
    path('register-staff/', views.registerstaff, name='register_teacher'),
    path('disable-staff/', views.disablestaff, name='disable_staff'),
    path('enable-staff/', views.enablestaff, name='enable_staff'),
    path('manage-staff/entry/', views.getstaff, name='get_staff'),
    path('manage-staff/<str:pk>/', views.managestaff, name='manage_staff'),
    path('edit-staff-reg/', views.editstaffreg, name='edit_staff_reg'),
    path('assessment/', views.assessment, name='assessment'),
    path('project/', views.project, name='project'),
    path('test/', views.test, name='test'),
    path('exam/', views.exam, name='exam'),
    path('superadmin/', views.superadmin, name='superadmin'),
    path('result-template/', views.resulttemplate, name='result_template'),
    path('term-result/', views.termresult, name='term_result'),
    path('result-upload/', views.resultupload, name='result_upload'),
    path('result/upload/', views.getstudentresult, name='get_result'),
    path('result/<str:pk>/', views.displayresult, name='display_result'),
    path('result-comment/', views.resultcomment, name='result_comment'),
    path('result-remove/', views.removeresult, name='result_remove'),
    path('result-approve/', views.approveresult, name='result_approve'),
    path('result-compute/', views.resultcomputation, name='result_compute'),
    path('result-start/', views.startresult, name='start_result'),
    path('result-status/', views.resultstatus, name='result_status'),
    path('approve/class/result/',views.approveclassresult, name='approve_class_result'),
    path('result-approve/<str:pk>', views.approveresultclick, name='approve'),
    path('attendance/', views.attendance, name='attendance'),
    path('attendance/present/<str:id>/', views.present, name='pattendance'),
    path('attendance/absent/<str:id>/', views.absent, name='aattendance'),
    path('attendance/unlock/', views.unlockattendance, name='unlock'),
    path('generate-card/', views.generatecard, name='generatecard'),
    path('user/profile/', views.userprofile, name='userprofile'),
    # path('user/profile/<str:pk>/', views.userprofile, name='profile'),

    path('password-reset/',auth_views.PasswordResetView.as_view(template_name='application/password_reset.html'), name='password_reset'),
    path('password-reset/done/',auth_views.PasswordResetDoneView.as_view(template_name='application/password_reset_done.html'), name='password_reset_done'),
    path('password-reset-confirm/<uidb64>/<token>/',auth_views.PasswordResetConfirmView.as_view(template_name='application/password_reset_confirm.html'), name='password_reset_confirm'),
    path('password-reset-complete/',auth_views.PasswordResetCompleteView.as_view(template_name='application/password_reset_complete.html'), name='password_reset_complete'),
]